# Generated by Django 4.2.5 on 2023-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kokalekua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=250)),
                ('pisua', models.CharField(max_length=2)),
                ('sortua', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liburua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulua', models.CharField(max_length=250)),
                ('egilea', models.CharField(max_length=50)),
                ('orrialde_kopurua', models.CharField(max_length=6)),
                ('generoa', models.CharField(max_length=100)),
            ],
        ),
    ]
